# Generated by Django 4.0.4 on 2022-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accepteduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=5)),
                ('numb', models.IntegerField(default=0)),
            ],
        ),
    ]
